const data = {
    fullStack: [
        {
            id: 1,
            image: "mobile-shoppee.PNG",
            name: "Mobile Shoppee",
            desc: "This is my first ever php project, i built everything from front-end to back-end with my knowledge of php. The UI is pretty bad, Hahaha!!.",
            available: true,
            gitUrl: "https://github.com/fortuneCodeHub/MobileShoppe.git",
            url: "https://mobilegadgetshoppe.000webhostapp.com/",
            tech: ["HTML", "CSS", "Bootstrap 5", "JQuery", "PHP"],
        },
        {
            id: 2,
            image: "frames.PNG",
            name: "Frames",
            desc: "This is a PHP MVC Framework that i created from scratch, here i utilized all my PHP skills, I worked with OOP, composer autoloading of classes, MVC framework system, built a command line tool for it called Frames. It's a working progress, i am still building it to also work as an api with protection just like laravel:sanctum which makes api's protected and easy to build. I've not created a documentation on my github yet, it's just a simple framework you can utilize when building a project involving just PHP and no framework",
            available: false,
            gitUrl: "https://github.com/fortuneCodeHub/Frames.git",
            url: "",
            tech: ["HTML", "CSS", "Bootstrap 5", "PHP", "PHP_MVC", "PHP_OOP"],
        },
        {
            id: 3,
            image: "jj-codes.PNG",
            name: "JJ-CODES",
            desc: "This is a website that sells coding courses, it was built with AJAX, so it kinda feels like it's a fetching response from an API just that the api is in it's file system.It's file system is built like the mvc framework system, just that it's not complicated and it uses composer to autoload classes. It has a nice UI but i'm just bad with images that's all",
            available: true,
            gitUrl: "https://github.com/fortuneCodeHub/JJ-CODES.git",
            url: "https://jj-codes.pxxl.space/sites/jj-codes/drive/public/",
            tech: ["HTML", "CSS", "Bootstrap 5", "Javascript", "PHP", "AJAX"],
        },
        {
            id: 4,
            image: "code-gigs.PNG",
            name: "Code GIGs",
            desc: "This is my first project with laravel, it has pagination, a search tool, it has CRUD(with posting of image), it manages job listing (i.e edit and delete), it utilizes middleware to give access belonging to who's a user and who's not a user",
            available: true,
            gitUrl: "https://github.com/fortuneCodeHub/CodeGIGs.git",
            url: "https://codegigs.pxxl.space/sites/codegigs/drive/public/",
            tech: ["HTML", "CSS", "Bootstrap 5", "Tailwind CSS", "Javascript", "PHP", "Laravel"],
        },
    ],
    frontEnd: [
        {
            id: 1,
            image: "sokachin.PNG",
            name: "Sokachin LTD",
            desc: "This is my first design project, i created it with just the basic design skills. It's a website for a construction company. The UI is very basic.",
            available: true,
            gitUrl: "https://github.com/fortuneCodeHub/SokachinLtd-Design.git",
            url: "https://fortunecodehub.github.io/SokachinLtd-Design/",
            tech: ["HTML", "CSS", "Bootstrap 5", "JQuery"],
        },
        {
            id: 2,
            image: "code-bootcamp.PNG",
            name: "CodeBootcamp",
            desc: "This is a one page website for buying subscribing for free code bootcamps.",
            available: true,
            gitUrl: "https://github.com/fortuneCodeHub/CodeBootcamp-Design.git",
            url: "https://fortunecodehub.github.io/CodeBootcamp-Design/",
            tech: ["HTML", "CSS", "Bootstrap 5", "Javascript"],
        },
        {
            id: 3,
            image: "landing-page.PNG",
            name: "Landing Page",
            desc: "This is a one page website for a landing page for a my company. The UI is not much but it just simple. Here i enhanced my javascript skills",
            available: true,
            gitUrl: "https://github.com/fortuneCodeHub/LandingPage-Design.git",
            url: "https://fortunecodehub.github.io/LandingPage-Design/",
            tech: ["HTML", "CSS", "Bootstrap 5", "Javascript"],
        },
        {
            id: 4,
            image: "proinvest.PNG",
            name: "ProInvest",
            desc: "This is a UI for making investment based on the plans given to you",
            available: true,
            gitUrl: "https://github.com/fortuneCodeHub/ProInvest-Design.git",
            url: "https://fortunecodehub.github.io/ProInvest-Design/",
            tech: ["HTML", "CSS", "Bootstrap 5", "Javascript"],
        },
        {
            id: 5,
            image: "adxpress.PNG",
            name: "ADXpress",
            desc: "This is an e-commerce website that i built from scratch without a template and just pure, clean code",
            available: true,
            gitUrl: "https://github.com/fortuneCodeHub/ADXpress.git",
            url: "https://fortunecodehub.github.io/ADXpress/",
            tech: ["HTML", "CSS", "Bootstrap 5", "Tailwind CSS", "Javascript", "JQuery"],
        },
        {
            id: 6,
            image: "verbo.PNG",
            name: "Verbo",
            desc: " This is a website for a social media application i plan to build. I utilized javascipt intersection observer alot, also monitored scroll postion which enabled me to create animations on scroll without using GSAP library scrollTrigger",
            available: true,
            gitUrl: "https://github.com/fortuneCodeHub/Verbo-Chat-Application.git",
            url: "https://fortunecodehub.github.io/Verbo-Chat-Application/",
            tech: ["HTML", "CSS", "Bootstrap 5", "Tailwind CSS", "Javascript"],
        },
        {
            id: 7,
            image: "portfolio1.PNG",
            name: "FortuneCodeHub First folio",
            desc: "My first portfolio site",
            available: true,
            gitUrl: "https://github.com/fortuneCodeHub/fortuneCodeHub.git",
            url: "https://fortunecodehub.github.io/fortuneCodeHub/",
            tech: ["HTML", "CSS", "Bootstrap 5", "Javascript"],
        },
    ]
}

export default data